Repository Planning-Inspectorate/service-common, pull requests merged in 2021-12, with the labels that each got.

#27 feat(clamav): update unit test + feature
  services/clamav/package-lock.json
  services/clamav/package.json
  services/clamav/src/index.js
  services/clamav/src/index.test.js
  services/clamav/tests/artifacts/default.csv
  services/clamav/tests/artifacts/default.docx
Labels: bug, enhancement

#30 refactor(as-3650): folder restructure and version upgrade
  services/clamav-rest-client/.eslintignore
  services/clamav-rest-client/.eslintrc
  services/clamav-rest-client/.gitignore
  services/clamav-rest-client/package-lock.json
  services/clamav-rest-client/package.json
  services/clamav-rest-client/src/index.js
  services/clamav-rest-client/src/index.test.js
  services/clamav-rest-client/tests/artifacts/default.csv
  services/clamav-rest-client/tests/artifacts/eicar.com.txt
Labels: enhancement

#31 feat(as-4237): magic link
  .idea/jsLibraryMappings.xml
  services/magic-link/.eslintignore
  services/magic-link/.eslintrc
  services/magic-link/.gitignore
  services/magic-link/package-lock.json
  services/magic-link/package.json
  services/magic-link/src/__tests__/magic-link.test.js
  services/magic-link/src/__tests__/resources/magicLinkData.json
  services/magic-link/src/__tests__/resources/magicLinkDataInvalid.json
  services/magic-link/src/__tests__/util/cryptoUtils.test.js
  services/magic-link/src/__tests__/util/dateUtil.test.js
  services/magic-link/src/config.js
  services/magic-link/src/error/ExpiredTokenError.js
  services/magic-link/src/error/InvalidTokenError.js
  services/magic-link/src/index.js
  services/magic-link/src/magic-link.js
  services/magic-link/src/util/cryptoUtils.js
  services/magic-link/src/util/dateUtil.js
  services/magic-link/src/validators/schema/magicLinkDataValidator.js
Labels: draft
